
name: Build, Deploy to AWS ECR, ECS, and Terraform Deployment

on:
  push:
    branches:
    - main
    - test

env:
  AWS_REGION: ap-south-1
  AWS_ACCOUNT_ID: 314146329517
  
jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Configure AWS Credentials.
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # Initialize Terraform
    - name: Terraform Init
      run: terraform init
      working-directory: ./tf

    # Plan Terraform changes
    - name: Terraform Plan
      run: terraform plan -out=tfplan
      working-directory: ./tf

    # Apply Terraform changes
    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: ./tf
